language: node_js
node_js:
- 10
sudo: required
addons:
  chrome: stable
branches:
  except:
    - gh-pages
install:
- npm install
script:
- npm run travis
after_script:
- cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
